coral/urls.py
from django.urls import path
from coral import views

from .views import  CreateCoralView # new
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', auth_views.LoginView.as_view(), name='login'),
    path("coral_list", views.index, name="index"),
    path("<int:pk>/", views.coral_detail, name="coral_detail"),
    path("newCoral/", CreateCoralView.as_view(), name="newCoral"),
    path("<int:pk>/photoUpdate", views.UpdatePhotoView.as_view(),name="photoUpdate"),
    path("<int:pk>/coralUpdate", views.UpdateCoralView.as_view(),name="coralUpdate"),
    path("<int:pk>/coralDelete",views.DeleteCoralView.as_view(),name="coralDelete"),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
] 

if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

coral_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  # new
from django.conf.urls.static import static  # new
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('coral.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('sales/', include('sales.urls')),

    
]

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coral/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import PIL.Image
import cv2
import matplotlib.pyplot as plt
import numpy as np

# Create your models here.
choices = [
    ('live', 'Live'),
    ('deceased',"Deceased")
]
species_Choices = [
        ('sps', 'SPS'),
        ('lps', 'LPS'),
        ('softy', 'Softy'),
        ('zoa', 'Zoa'),
        ('Algae', 'Algae'),
        ('Anemone', 'Anemone'),
        ('Gorgonian', 'Gorgonian'),
        # Add more choices as needed
    ]
class Coral(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    status = models.CharField(max_length=20,choices=choices)
    source = models.TextField() 
    purchaseDate = models.DateField()
    purchaseCost = models.DecimalField(max_digits=6, decimal_places=2)
    image = models.ImageField(upload_to='upload/',null=True, blank=True)
    date_created = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    species = models.CharField(max_length=100, choices=species_Choices,default='sps')
    def __str__(self):
        return self.name
    
#class User(models.Model):
#    first_name = models.CharField(max_length=100)
#   last_name = models.CharField(max_length=100)
    
class Photos(models.Model):
    coral = models.ForeignKey(Coral, on_delete=models.PROTECT,null=True, blank=True)
    image_date = models.DateField()
    images = models.ImageField(upload_to='upload/',null=True, blank=True)

    def crop_center(pil_img, crop_width, crop_height):
        img_width, img_height = pil_img.size
        return pil_img.crop(((img_width - crop_width) // 2,
                         (img_height - crop_height) // 2,
                         (img_width + crop_width) // 2,
                         (img_height + crop_height) // 2))

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        pil_img = PIL.Image.open(self.images)
        image = cv2.cvtColor(np.array(pil_img), cv2.COLOR_RGB2BGR)
        hgt, wdt = image.shape[:2]
        start_row, start_col = int(hgt * .05), int(wdt * .05)
        end_row, end_col = int(hgt * .95), int(wdt * .95)
        cropped = image[start_row:end_row , start_col:end_col]
        cropped_final = cv2.cvtColor(cropped, cv2.COLOR_BGR2RGB)
#       import numpy as np
        resized_img = cv2.resize(cropped_final, (500, 400), interpolation = cv2.INTER_LINEAR)
        pil_img_final = PIL.Image.fromarray(resized_img)

        #cv2.imwrite(self.images.path, cropped_final)

        
        pil_img_final.save(self.images.path, quality=100)
        pil_img_final.close()
        self.images.close()

        #super().save(*args, **kwargs)
        #pil_img = Image.open(self.images)
        #img = cv2.imread(pil_img)
        #image = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        #hgt, wdt = image.shape[:2]
        #start_row, start_col = int(hgt * .15), int(wdt * .15)
        #end_row, end_col = int(hgt * .85), int(wdt * .85)
        #cropped = image[start_row:end_row , start_col:end_col]
        #cropped_final = cv2.cvtColor(cropped, cv2.COLOR_BGR2RGB)
#
        #cv2.imwrite(self.images.path, cropped_final)
        #
#
        #self.images.close()

coral/forms.py
from django import forms
from django.forms import ModelForm, Select
from .models import Coral, Photos


class DateInput(forms.DateInput):
    input_type = 'date'

class photoForm(forms.ModelForm):
    class Meta:
        model = Photos
        fields = ['coral',"image_date","images"]
        widgets = {'image_date': DateInput(),}
class CoralForm(forms.ModelForm):

    class Meta:
        model = Coral
        fields = [
            "name",
            "description",
            "status",
            "source",
            "purchaseDate",
            "purchaseCost",
            "image",
            'user']
        widgets = {
            'purchaseDate': DateInput(),
            'status': Select(),
        }
class CoralFilterForm(forms.Form):
    pass

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

coral/views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from django.http import HttpResponse
from coral.models import Coral, Photos
from django.views.generic import ( CreateView, UpdateView,DeleteView,DetailView, ) # new
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy  # new
from .forms import CoralForm, LoginForm, photoForm  # new
from django.views.generic import CreateView
from django.db.models import Sum
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import CoralFilterForm

# Create your views here.

def login_user(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,
                                username=cd['username'],
                                password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Authenticated successfully')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'registration/login.html', {'form': form})

#@login_required
def accounting(request):
    #purchaseDate  = Coral.objects.values('purchaseDate', 'purchaseCost').distinct()

    

    values = Coral.objects.filter().values('purchaseDate').order_by('purchaseDate').annotate(sum=Sum('purchaseCost'))
    context = {
        'purchaseDate': values,
        'sum' : sum
        
    }
    return render(request, 'accounting.html', context)
    
def index(request):
    user = request.user
    coral_name_filter = request.GET.get('coral_name', '')
    species_filter = request.GET.get('species', '')
    #coral = Coral.objects.filter(user=request.user).order_by('name')
    coral_queryset = Coral.objects.filter(user=request.user).order_by('name')

    # Apply the search filter if a search term is provided
    if coral_name_filter:
        coral_queryset = coral_queryset.filter(name__icontains=coral_name_filter)

    # Apply the species filter if a species is selected
    if species_filter:
        coral_queryset = Coral.objects.all().values('species').distinct()
    print(coral_queryset)
    paginator = Paginator(coral_queryset, per_page=12)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'corals': page_obj,
        'coral_name_filter': coral_name_filter,
        'species_filter': species_filter,  # Pass the filter value to the template
    }
    return render(request, 'index.html', context)

#@login_required
def coral_detail(request, pk):
    coral = Coral.objects.get(pk=pk)
    images = Photos.objects.filter(coral=coral)
    print(images)
    context = {
        'coral': coral,
        'images': images
    }
    return render(request, 'coral_detail.html', context)
#@login_required
class CreateCoralView(SuccessMessageMixin,CreateView):  # new
    model = Coral
    form_class = CoralForm
    template_name = "newCoral.html"
    success_message = "Your coral was added!"
    success_url = reverse_lazy("index")
    
#@login_required
class UpdatePhotoView(SuccessMessageMixin, CreateView):
    model = Photos
    form_class = photoForm
    template_name = "growthShotUpdate.html"
    

    success_message = "Your photo was added!"
    success_url = reverse_lazy("index")

#@login_required
class UpdateCoralView(SuccessMessageMixin, UpdateView):
    model = Coral
    template_name = "updateCoral.html"
    form_class = CoralForm

    success_message = "Your entry was updated!"
    success_url = reverse_lazy("index")
    
#@login_required
class DeleteCoralView(DeleteView):
    model = Coral
    form_class = CoralForm
    template_name = "coralDelete.html"
    success_message = "Your entry was deleted!"
    success_url = reverse_lazy("index")
    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super().delete(request, *args, **kwargs)

coral/templates/accounting.html
{% extends "base.html" %}
{% load static %}
{% block page_content %}

<table>
    <tr>
        <th>Date</th>
        <th>Cost</th>
    </tr>
    {% for date in purchaseDate %}
    <tr>
        <td>{{ date.purchaseDate }}</td> 
        <td>{{ date.sum|floatformat:2 }}</td> 
    </tr>
    {% endfor %}
</table>


{% endblock %}

coral/templates/base.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Coral Directory</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          {% if request.user.is_authenticated %}
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" a href="/dashboard">Dashboard</a>
            </li>
           
            <li class="nav-item">
              <a class="nav-link" a href="/sales">Sales</a>
            </li>
          </ul>
          {% endif %}
              <span class="user">
                {% if request.user.is_authenticated %}
                  Hello {{ request.user.first_name|default:request.user.username }},
                  <a href="{% url "logout" %}">Logout</a>
                {% else %}
                  <a href="{% url "login" %}">Log-in</a>
                {% endif %}
              </span>
          
        </div>
    </div>

</nav>





{% for message in messages %}
<div class="container-fluid p-0">
  <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="True">&times;</span>
    </button>
    {{ message }}
  </div>
</div>
{% endfor %}

<div class="container">
    {% block page_content %}{% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css">
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

coral/templates/coralDelete.html
{% extends "base.html" %}




{% block page_content %}


<form method="post">{% csrf_token %}
    <p>
        Are you sure you want to delete
        <em>"{{ coral.name }}"</em>
        created on {{ coral.date_created|date:'Y-m-d' }}?
    </p>
    <input type="submit" value="Confirm">
</form>
<a href="{% url 'coral_detail' coral.pk %}">
    <button>Cancel</button>
</a>
{% endblock %}

coral/templates/coral_detail.html
{% extends "base.html" %}
{% load static %}

{% block page_content %}
<h1>{{ coral.name }}</h1>
<p>
    <a href="{% url 'coralUpdate' coral.pk %}">✍️ Edit</a>
    <a href="{% url 'photoUpdate' coral.pk %}">✍️ Growth Photo</a>
    <a href="{% url 'coralDelete' coral.pk %}">⛔ Delete</a>

</p>
<div class="row">
    <div class="col-md-8">
        <img src="{{coral.image.url}}" alt="" width="100%">
    </div>
    <div class="col-md-4">
        <h5>About the coral:</h5>
        <p>{{ coral.description }}</p>
        <br>
        <h5>Purchase Date:</h5>
        <p>{{ coral.purchaseDate }}</p>
    </div>
</div>

<div class="row">
<h3>
    <br></br>
    <span class="label">Growth Photos</span>
</h3>
</div>
    <div class="row">
        
        {% for i in images %}
            <div class="col-md-20">
                <div class="card mb-20">
             
                    <div class="card-body">
                        <h5 class="card-title">{{ i.image_date }}</h5>
                        <img class="card-img-top" src="{{ MEDIA_URL }}{{i.images.url}}">
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
{% endblock %}

coral/templates/growthShotUpdate.html
{% extends "base.html" %}
{%load crispy_forms_tags %} 
{% block page_content %}
<h1>Create New Coral</h1>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{  form|crispy }}
  <button type="submit">Submit New photo</button>
</form>

{% endblock %}

coral/templates/hello_world.html
<h1>Hello, World!</h1>

coral/templates/index.html
{% extends "base.html" %}

{% load static %}
{% block page_content %}

<h1>Corals</h1>

<button type="button" class="btn btn-primary"> 
    <a href="newCoral" style="color:inherit">Add Coral</a>
</button>
<form method="get" action="{% url 'index' %}">
  <!-- Search input -->
  <label for="coral_name">Coral Name:</label>
  <input type="text" name="coral_name" value="{{ coral_name_filter }}">
  <button type="submit">Search</button>
</form>
  <br>

  <!-- Species dropdown -->
  <form method="get" action="{% url 'index' %}">
    <label for="id_species">Species:</label>
    <select name="species" id="id_species">
      <option value="">All Species</option>
      {% for species in unique_species %}
        <option value="{{ species }}" {% if species_filter == species %}selected{% endif %}>{{ species }}</option>
      {% endfor %}
    </select>
    <button type="submit">Filter</button>
  </form>
<div class="row">
    {% for coral in corals %}
    <div class="col-md-4">
        <div class="card mb-2">
            <img class="card-img-top" src="{{ MEDIA_URL }}{{ coral.image.url }}">
            <div class="card-body">
                <h5 class="card-title">{{ coral.name }}</h5>
                <p class="card-text">{{ coral.description }}</p>
                <a href="{% url 'coral_detail' coral.pk %}" class="btn btn-primary">
                    Read More
                </a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<div class="pagination d-flex justify-content-center">
    <ul class="pagination">
      {% if corals.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ corals.previous_page_number }}">Previous</a>
        </li>
      {% endif %}
  
      <li class="page-item active">
        <span class="page-link">{{ corals.number }} of {{ corals.paginator.num_pages }}</span>
      </li>
  
      {% if corals.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ corals.next_page_number }}">Next</a>
        </li>
      {% endif %}
    </ul>
  </div>

{% endblock %}

coral/templates/newCoral.html
{% extends "base.html" %}
{%load crispy_forms_tags %} 
{% block page_content %}
<h1>Create New Coral</h1>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{  form|crispy }}
  <button type="submit">Submit New Coral</button>
</form>

{% endblock %}

coral/templates/updateCoral.html
{% extends "base.html" %}
{%load crispy_forms_tags %} 
{% block page_content %}
<h1>Create New Coral</h1>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{  form|crispy }}
  <button type="submit">Submit New Coral</button>
</form>

{% endblock %}